export type Lang = 'en' | 'my';

export const strings = {
  en: {
    // Bottom Nav
    nav_home: 'Home',
    nav_dashboard: 'Dashboard',
    nav_budget: 'Budget',
    nav_transactions: 'Transactions',
    nav_profile: 'Profile',
    // Settings Menu
    settings_title: 'Settings',
    settings_admin_panel: 'Admin Panel',
    settings_api_credentials: 'Storage & API',
    settings_notion_guide: 'Notion Guide',
    settings_customize: 'Groups & Categories',
    settings_history: 'History',
    settings_auto_payments: 'Auto Payments',
    settings_backup: 'Backup & Restore',
    settings_contact: 'Contact',
    settings_language: 'Language',
    // Auth
    auth_sign_in: 'Sign In',
    auth_sign_up: 'Sign Up',
    auth_sign_out: 'Sign Out',
    auth_email: 'Email',
    auth_password: 'Password',
    auth_forgot_password: 'Forgot Password?',
    auth_reset_password: 'Reset Password',
    auth_confirm_password: 'Confirm Password',
    auth_new_password: 'New Password',
    auth_signup_success: 'Sign up successful! Please check your email for verification.',
    auth_signin_success: 'Sign in successful!',
    auth_reset_email_sent: 'Password reset email sent!',
    auth_password_changed: 'Password changed. Please sign in again.',
    auth_password_mismatch: 'Passwords do not match. Please check again.',
    auth_password_too_short: 'Password must be at least 6 characters.',
    // Buttons
    btn_save: 'Save',
    btn_delete: 'Delete',
    btn_cancel: 'Cancel',
    btn_confirm: 'Confirm',
    btn_close: 'Close',
    btn_edit: 'Edit',
    btn_add: 'Add',
    btn_send: 'Send',
    btn_load_more: 'Load More ({count} remaining)',
    btn_got_it: 'Got it',

    btn_backup_now: 'Backup Now',
    btn_restore: 'Restore',
    btn_replace: 'Replace',
    btn_merge: 'Merge',
    // Dashboard
    dashboard_title: 'Dashboard',
    dashboard_overview: 'Overview',
    dashboard_income: 'Income',
    dashboard_expense: 'Expense',
    dashboard_balance: 'Balance',
    dashboard_by_group: 'By Group',
    dashboard_monthly_trend: 'Monthly Trend',
    dashboard_expense_by_group: 'Expense by Group',
    dashboard_current: 'Current',
    dashboard_tap_to_view: 'tap to view details',
    dashboard_of_budget: 'of budget',
    dashboard_no_budget_set: 'No budget set',
    dashboard_left: 'left',
    // Home / Input
    input_placeholder: 'Type your expense or income...',
    input_listening: 'Listening...',
    input_ai_parsing: 'AI parsing...',
    input_required: 'Please enter some text or attach an image.',
    input_ai_success: 'AI parsing successful.',
    input_send_to_notion: 'Send to Notion',
    input_save_to_app: 'Save to App',
    // Parsed Entries
    parsed_title: 'Parsed Entries',
    parsed_empty: 'No entries parsed yet.',
    parsed_item: 'Item',
    parsed_group: 'Group',
    parsed_category: 'Category',
    parsed_date: 'Date',
    parsed_amount: 'Amount',
    parsed_type: 'Type',
    // Toast
    toast_entry_saved: 'Entry saved successfully.',
    toast_entries_saved: '{count} entries saved successfully.',
    toast_entry_deleted: 'Entry deleted.',
    toast_entries_deleted: '{count} entries deleted.',
    toast_entry_updated: 'Entry updated.',
    toast_budget_exceeded: '⚠ Budget exceeded for {group}! ({spent} / {limit})',
    toast_notion_all_success: 'All {count} entries sent to Notion successfully.',
    toast_notion_partial: '{success} succeeded, {failed} failed.',
    toast_notion_all_failed: 'All entries failed to send.',
    toast_notion_missing: 'Notion API Key or Database ID required. Please add in Settings.',
    toast_settings_saved: 'Settings saved to cloud.',
    toast_settings_load_failed: 'Failed to load settings.',
    toast_budget_saved: 'Budget saved for {group}.',
    toast_budget_save_failed: 'Failed to save budget.',
    toast_budget_deleted: 'Budget for {group} deleted.',
    toast_budget_delete_failed: 'Failed to delete budget.',
    toast_backup_load_failed: 'Failed to load backup list.',
    toast_backup_failed: 'Backup failed.',
    toast_backup_saved: 'Backup saved. ({count} entries)',
    toast_restore_failed: 'Restore failed.',
    toast_restore_success: 'Restore successful. ({count} entries)',
    toast_backup_deleted: 'Backup deleted.',
    toast_backup_delete_failed: 'Failed to delete backup.',
    toast_role_changed: 'Role changed to {role}.',
    toast_account_deleted: 'Account for {email} has been deleted.',
    // Errors
    error_gemini_quota: 'Gemini API quota exceeded. Please wait and try again.',
    error_gemini_invalid_key: 'Invalid Gemini API Key. Please check in Settings.',
    error_server_busy: 'Server is busy. Please try again.',
    error_content_blocked: 'Content could not be processed. Please try different text.',
    error_notion_invalid_key: 'Invalid Notion API Key. Please check your Integration Token in Settings.',
    error_notion_db_not_found: 'Notion Database not found. Please verify the Database ID and Integration connection.',
    error_notion_no_access: 'Integration has no access to this Database. Go to Database → Share → add Integration.',
    error_notion_validation: 'Notion column names incorrect. Required: Date, Item, Group, Category, Income, Expense.',
    error_unauthorized: 'Connection unauthorized. Your API Key or Token may have expired.',
    error_invalid_credentials: 'Invalid email or password. Please try again.',
    error_user_registered: 'An account with this email already exists.',
    error_email_not_confirmed: 'Email verification required. Please check your inbox.',
    error_session_expired: 'Session expired. Please sign in again.',
    error_network: 'Poor internet connection or unable to reach server.',
    error_timeout: 'Connection timed out. Please try again.',
    error_image_too_large: 'Image size exceeds 3MB. Please reduce the image size.',
    error_unexpected: 'An unexpected error occurred. Please try again.',
    // Approval Popup
    // History
    history_title: 'History',
    history_search_placeholder: 'Search...',
    history_empty: 'No history yet.',
    history_delete_confirm: 'Are you sure you want to delete {count} entries?',
    history_entry_deleted: 'Entry deleted successfully.',
    // Backup
    backup_count: '{count} backups stored',
    backup_empty: 'No backups yet.',
    backup_empty_hint: 'Press "Backup Now" to save one.',
    backup_merge_hint: '✦ Current entries kept. Backup entries will be merged in.',
    backup_replace_hint: '⚠️ All current entries will be deleted and replaced with backup.',
    backup_delete_confirm: 'Are you sure you want to delete this backup?',
    backup_replace_confirm: 'Are you sure you want to restore (Replace)?',
    backup_merge_confirm: 'Are you sure you want to restore (Merge)?',
    backup_delete_warning: 'This backup will be permanently deleted.',
    backup_replace_warning: 'All current entries will be deleted.',
    backup_merge_desc: '{count} entries from backup will be merged with current data.',
    backup_replace_desc: '{count} entries from backup will be restored.',
    // Admin
    admin_title: 'Admin Panel',
    admin_delete_confirm: 'All data for "{email}" will be permanently deleted. This cannot be undone.',
    admin_promote: 'Promote to Admin',
    admin_demote: 'Remove Admin',
    // Voice
    voice_not_supported: 'Voice recognition not supported in this browser.',
    voice_no_speech: 'No speech detected. Please try again.',
    voice_no_speech_timeout: 'No speech detected for 5 seconds. Auto-stopped.',
    voice_mic_denied: 'Microphone access denied. Please allow microphone permission.',
    voice_failed: 'Voice recognition failed.',
    // Profile
    profile_title: 'Profile',
    profile_email: 'Email',
    profile_role: 'Role',
    profile_storage_mode: 'Storage Mode',
    profile_member_since: 'Member since',
    profile_app_version: 'App Version',
    // Misc
    api_credentials_required: 'API Credentials Required',
    api_credentials_desc: 'Please fill in your Gemini Key, Notion Key, and Database ID in Settings.',
    confirm_delete_entry: 'Delete "{item}"?',
    error_occurred: 'An Error Occurred',
    loading: 'Loading...',
    saving: 'Saving...',
    no_data: 'No data available.',
    optional: 'Optional',

    // --- Dashboard extra ---
    dashboard_entries: 'Entries',
    dashboard_summary: 'Summary',
    dashboard_over_by: 'Over by',
    dashboard_saving_rate: 'Saving Rate',
    dashboard_monthly_overview: 'Monthly Overview',
    dashboard_top_categories: 'Top Categories',
    dashboard_year_income: 'Year Income',
    dashboard_year_expense: 'Year Expense',
    // --- DataTable ---
    col_item_date: 'Item / Date',
    col_amount: 'Amount',
    col_category: 'Category',
    col_category_group: 'Category / Group',
    table_header_entries: 'Entries',
    filter_year: 'Year',
    filter_month: 'Month',
    filter_type: 'Type',
    filter_group: 'Group',
    filter_category: 'Category',
    filter_income: 'Income',
    filter_expense: 'Expense',
    filter_all: 'All',
    btn_clear_filters: 'Clear Filters',
    export_rows: 'Export {count} rows',
    search_placeholder: 'Search...',
    no_entries_found: 'No entries found',
    delete_entry_title: 'Delete Entry',
    delete_entry_desc: 'Delete "{item}"? This cannot be undone.',
    parsed_tap_to_edit: 'Tap to edit',
    parsed_send_to_notion: 'Send to Notion',
    parsed_save_entries: 'Save Entries',
    input_welcome: 'Welcome back! What did you spend today?',
    input_upload_prompt: 'Tap to upload image',
    input_upload_hint: 'JPG, PNG up to 3MB',
    input_parse_btn: 'ANALYZE',
    profile_preferences: 'Preferences',
    profile_account_security: 'Account & Security',
    profile_storage_hint: 'Where your data is stored',
    profile_app_only: 'App Only',
    profile_notion_sync: 'Notion Sync',
    profile_joined: 'Joined',
    profile_add_display_name: '+ Add display name',
    profile_display_name_placeholder: 'Display name',
    profile_theme_current: 'Currently {mode}',
    profile_dark_mode: 'Dark Mode',
    profile_light_mode: 'Light Mode',
    profile_change_password: 'Change Password',
    profile_new_password: 'New Password',
    profile_confirm_password: 'Confirm Password',
    profile_delete_account: 'Delete Account',
    profile_notion_requires: 'Notion Sync requires Premium or Admin role.',
    entry_add_title: 'Add Entry',
    entry_edit_title: 'Edit Entry',
    entry_add_new: 'Add New',
    entry_item_name: 'Item Name',
    entry_amount: 'Amount',
    entry_date: 'Date',
    entry_group: 'Group',
    entry_category: 'Category',
    entry_save: 'Save',
    entry_select_group: 'Select group',
    entry_select_category: 'Select category',
    entry_group_name_placeholder: 'Group name',
    entry_category_name_placeholder: 'Category name',
    entry_picker_group: 'Group',
    entry_picker_category: 'Category',
    contact_desc: 'Need help or want to report a bug? Reach out via the links below.',
    budget_tab_limits: 'Group Limits',
    budget_tab_allocation: 'Allocation Table',
    budget_group_limits: 'Group Budget Limits',
    budget_total: 'Total',
    budget_spent: 'Spent',
    budget_used: 'Used',
    budget_over_by: 'Over by',
    budget_no_limit: 'No limit',
    budget_allocation_balance: 'Unallocated',
    budget_limit_help: 'You can customize your groups in Settings',
    api_keys_title: 'API Keys',
    api_app_desc: 'App Only mode — Gemini key required.',
    autopay_empty: 'No auto payments yet.',
    autopay_new_title: 'New Auto Payment',
    autopay_edit_title: 'Edit Auto Payment',
    autopay_btn_add: 'Add Payment',
    autopay_premium_only: 'Auto Payments is a Premium feature.',
    autopay_active_info: 'Active payments run automatically when you open the app.',
    btn_run_now: 'Run Now',
    btn_save_changes: 'Save Changes',
    btn_save_settings: 'Save Settings',
    premium_feature: 'Premium Feature',
    scan_premium_desc: 'Receipt scanning is available for Premium users only.',
    deleting: 'Deleting...',
    saved: 'Saved',
    toast_name_updated: 'Display name updated.',
    toast_name_failed: 'Failed to update name.',
    toast_avatar_updated: 'Avatar updated.',
    toast_avatar_failed: 'Failed to update avatar.',
    toast_pw_too_short: 'Password must be at least 6 characters.',
    toast_pw_mismatch: 'Passwords do not match.',
    toast_pw_changed: 'Password changed successfully.',
    toast_pw_failed: 'Failed to change password.',
    toast_account_deleted_self: 'Account deleted.',
    toast_delete_failed: 'Failed to delete account.',
    toast_item_required: 'Item name is required.',
    toast_amount_required: 'Amount is required.',
    toast_save_failed: 'Save failed.',
    toast_update_failed: 'Update failed.',
    toast_deleted: 'Deleted.',
    toast_updated: 'Updated.',
    toast_autopay_added: 'Auto payment added.',
    notification_title: 'Notifications',
    notification_mark_all: 'Mark all as read',
    notification_empty: 'No notifications yet',
    notification_recent: 'Recent Updates',
    toast_autopay_load_failed: 'Failed to load auto payments.',
    toast_no_payments_due: 'No payments due.',
    toast_run_failed: 'Failed to run payments.',
    required: 'Required',


    profile_mode_dark: 'Dark',
    profile_mode_light: 'Light',
    auth_no_account: "Don't have an account? Sign Up",
    auth_have_account: 'Already have an account? Sign In',
    tab_text: 'Text',
    tab_scan: 'Scan Image',
    tab_file: 'File Upload',
    home_recent_activity: 'Recent activity',
    home_see_all: 'See All',
    budget_group_limits_label: 'GROUP BUDGET LIMITS',
    settings_backup_restore: 'Backup & Restore',

    auth_subtitle: 'Your personal expense companion.',
    auth_app_name: 'Notion-Ex Tracker',
    auth_username: 'Username',
    auth_username_placeholder: 'Your display name',
    auth_email_label: 'Email address',
    auth_email_placeholder: 'you@example.com',
    auth_password_label: 'Password',
    auth_or_continue: 'or continue with',
    auth_create_account: 'Create Account',
    auth_forgot_link: 'Forgot password?',
    auth_send_reset: 'Send Reset Link',
    auth_back_to_signin: 'Back to Sign In',
    auth_reset_enter_email: "Enter your email and we'll send you a reset link.",
    auth_check_email_title: 'Check your email 📬',
    auth_check_email_body: 'We sent a reset link to {email}. Click the link to reset your password.',
    auth_spam_hint: "Don't see it? Check your spam folder.",
    auth_set_new_password: 'Set new password',
    auth_new_password_placeholder: 'At least 6 characters',
    auth_confirm_password_label: 'Confirm password',
    auth_confirm_password_placeholder: 'Repeat password',
    auth_passwords_no_match: 'Passwords do not match',

    dashboard_app_only: 'Dashboard is available in App Only mode.',
    dashboard_entries_count: 'Entries ({count})',

    // Home / App header
    home_tagline: 'Track smarter, Sync better with Notion-Ex',

    // App.tsx & BudgetSettings
    toast_autopay_triggered: 'Auto payment added: {items}',
    budget_limit_placeholder: 'Leave empty to remove limit',

    // Camera / Gallery
    input_gallery_btn: 'Gallery',
    input_camera_btn: 'Camera',
    camera_capture_title: 'Take Photo',

    // AuthForm toast messages
    toast_username_required: 'Please enter a username.',
    toast_signup_success: 'Sign up successful! Please check your email for verification.',
    toast_signin_success: 'Sign in successful!',
    toast_pw_reset_sent: 'Password reset email sent!',
    toast_pw_changed_signin: 'Password changed successfully. Please sign in again.',
    toast_pw_mismatch_check: 'Passwords do not match. Please check again.',
    auth_update_password: 'Update Password',

    // NotionGuide
    notion_guide_banner_title: 'Notion Sync requires Premium',
    notion_guide_banner_desc: 'Notion Sync is available for Premium users only. Upgrade to sync your expenses directly to your Notion database.',
    notion_guide_banner_btn: '👑 Upgrade to Premium',
    notion_guide_divider: 'How to Set Up Notion',
    notion_guide_template_title: 'Notion Template',
    notion_guide_template_subtitle: 'Download & Duplicate to your workspace',
    notion_guide_template_open: 'Open',
    notion_guide_steps_label: 'Step-by-Step Setup Guide',
    notion_step1_title: 'Copy the Notion Template',
    notion_step1_li1: 'Click the "Copy Notion Template" button above',
    notion_step1_li2: 'A Notion page will open — click Duplicate in the top-right corner',
    notion_step1_li3: 'A Database will be duplicated into your Notion workspace',
    notion_step1_tip: 'It will contain exactly 6 columns: Date, Item, Income, Expense, Group, Category',
    notion_step2_title: 'Create a Notion Integration',
    notion_step2_li1: 'Go to notion.so/profile/integrations in your browser',
    notion_step2_li2: 'Click New integration button',
    notion_step2_li3: 'Enter a name (e.g. Ex Tracker)',
    notion_step2_li4: 'Select your workspace and click Save',
    notion_step2_li5: 'Copy the Internal Integration Secret (token)',
    notion_step2_tip: 'The token starts with ntn_ or secret_ — keep it private',
    notion_step3_title: 'Connect Database to Integration',
    notion_step3_li1: 'Open the duplicated Database page',
    notion_step3_li2: 'Click ••• (three dots) at the top right',
    notion_step3_li3: 'Connections → Connect to, then select your Integration',
    notion_step3_tip: 'Skipping this step will cause a "permission denied" error when sending data',
    notion_step4_title: 'Find Your Database ID',
    notion_step4_li1: 'Open the Database page in your browser',
    notion_step4_li2: 'Look at the URL — it will look like this:',
    notion_step4_li3: 'The part highlighted in green before ?v= (32 characters) is the Database ID',
    notion_step4_tip: 'If the URL contains /, take the part after the last slash',
    notion_step5_title: 'Add Keys to the App',
    notion_step5_li1: 'Go to Settings → API credentials',
    notion_step5_li2: 'Notion Integration Token field — paste the token from Step 2',
    notion_step5_li3: 'Notion Database ID field — paste the ID from Step 4',
    notion_step5_li4: 'Click Save — Setup complete! 🎉',
    notion_step5_tip: 'After saving, try parsing one entry and check if it appears in Notion',

    // SettingsDrawer
    settings_history_title: 'History',

    // AdminPanel
    admin_col_members: 'Members',
    admin_col_premium: 'Premium',
    admin_col_admins: 'Admins',
    admin_search_placeholder: 'Search user...',
    admin_col_email: 'EMAIL',
    admin_col_status: 'STATUS',
    admin_no_users: 'No users found',
    admin_badge_you: 'You',
    admin_status_active: '✓ Active',
    admin_user_info: 'User Info',
    admin_entries_label: 'Entries',
    admin_last_active: 'Last Active',
    admin_set_role: 'Set Role',
    admin_delete_account_btn: 'Delete Account',
    admin_ban_btn: 'Ban / Suspend',
    admin_unban_btn: 'Unban',
    admin_banned_badge: 'Banned',
    admin_ban_confirm: 'Ban "{email}"? They will be unable to sign in.',
    admin_unban_confirm: 'Unban "{email}"? They will be able to sign in again.',
    admin_set_expiry: 'Set Premium Expiry',
    admin_expiry_label: 'Premium Expires',
    admin_expiry_none: 'No expiry',
    admin_expiry_save: 'Save Expiry',
    admin_expiry_clear: 'Clear Expiry',
    admin_manage_title: 'Manage User',
    admin_tab_general: 'General',
    admin_tab_security: 'Security',
    admin_add_days_label: 'Add Premium Days',
    admin_add_days_btn: 'Add Days',
    admin_reset_plan_btn: 'Reset to Free',
    admin_reset_plan_confirm: 'Reset this user to Free plan?',
    admin_send_reset_email: 'Send Password Reset',
    admin_status_control: 'Status Control',
    toast_days_added: '{days} days added.',
    toast_plan_reset: 'Plan reset to Free.',
    toast_reset_email_sent: 'Password reset email sent.',
    toast_user_banned: '{email} has been banned.',
    toast_user_unbanned: '{email} has been unbanned.',
    toast_expiry_saved: 'Premium expiry saved.',
    toast_expiry_cleared: 'Premium expiry cleared.',
    toast_premium_updated: 'Premium subscription updated.',
    toast_payment_approved: 'Payment request approved.',
    toast_payment_rejected: 'Payment request rejected.',
    toast_payment_undone: 'Payment status reverted to pending.',
    toast_password_reset_sent: 'Password reset email sent successfully.',
    payment_reject_reason_label: 'Reason for rejection (optional)',
    payment_reject_reason_placeholder: 'e.g. Invalid transaction ID, screenshot unclear...',
    payment_reject_btn: 'Reject',
    payment_undo_btn: 'Undo',
    payment_undo_confirm: 'Reset this payment back to pending?',
    payment_details_label: 'Details',
    payment_note_label: 'Admin Note',

    // ApiSettings
    api_storage_mode_label: 'Storage Mode',
    api_app_only_title: 'App Only',
    api_app_no_notion: 'No Notion needed.',
    api_selected: 'Selected ✓',
    api_notion_sync_title: 'Notion Sync',
    api_notion_sync_desc: 'Sync to Notion DB. Requires API keys.',
    api_premium_required: 'Premium or Admin role required.',
    api_keys_label: 'API Keys',
    api_gemini_label: 'Gemini API Key',
    api_required_badge: 'Required',
    api_notion_key_label: 'Notion API Key',
    api_notion_credentials: 'Notion Credentials',
    api_database_id_label: 'Database ID',

    // HistorySettings
    history_sort_prefix: 'Sort:',
    history_delete_bulk_btn: 'Delete',
    history_select_all: 'Select All',
    history_deselect_all: 'Deselect All',
    history_col_item_date: 'Item / Date',
    history_col_category: 'Category',
    history_col_amount: 'Amount',
    history_sort_newest: 'Newest',
    history_sort_day: 'Day',
    history_sort_month: 'Month',
    history_sort_year: 'Year',

    // AutoPayments
    autopay_header_title: 'Auto Payments',
    autopay_active_count: '{count} active · runs on app open',
    autopay_run_now: 'Run Now',
    autopay_add_btn: 'Add',
    autopay_item_label: 'Item Name *',
    autopay_item_placeholder: 'e.g. Home Tax',
    autopay_amount_label: 'Amount *',
    autopay_amount_placeholder: '40000',
    autopay_type_expense: '💸 Expense',
    autopay_type_income: '💰 Income',
    autopay_category_label: 'Category',
    autopay_group_label: 'Group',
    autopay_day_label: 'Day of Month *',
    autopay_day_hint: 'Every month on the',
    autopay_last_run: 'Last run:',
    autopay_day_badge: 'DAY',
    autopay_select_placeholder: '— Select —',

    // CustomizeSettings
    customize_search_placeholder: 'Search {label}...',
    customize_type_placeholder: 'Type {label} name...',
    customize_add_btn: 'Add',
    customize_sort_az: 'A → Z',
    customize_sort_za: 'Z → A',
    customize_sort_default: 'Default',
    customize_no_items: 'No {label} found',
    customize_save_btn: 'Save Changes',
    customize_groups_tab: 'Groups',
    customize_categories_tab: 'Categories',

    // BackupRestore
    backup_premium_title: 'Premium Feature',
    backup_premium_desc: 'Backup & Restore is available for Premium users only.',
    backup_restore_mode_label: 'Restore Mode',
    backup_mode_merge: '🔀 Merge',
    backup_mode_replace: '♻️ Replace',
    backup_loading: 'Loading...',
    backup_entries_label: 'entries',

    // Profile roles & delete modal
    role_admin: 'Admin',
    role_premium: 'Premium',
    role_member: 'Member',
    profile_delete_desc: 'This will permanently delete all your entries, settings, and budgets.',
    profile_delete_type: 'Type {word} to proceed.',
    pull_to_refresh: 'Pull to refresh',
    release_to_refresh: 'Release to refresh',
    refreshing: 'Refreshing...',
    feature_unavailable_title: 'Feature Unavailable',
    feature_unavailable_desc: 'This feature is not available in Notion Sync mode. Switch to App Only mode in Profile.',
    go_to_settings: 'Go to Settings',
    voice_input_title: 'Voice Input',
    upload_photo_title: 'Upload Photo',
    voice_resume_title: 'Resume',
    voice_pause_title: 'Pause',
    voice_stop_title: 'Stop',

    // CSV Import
    csv_only_csv_allowed: 'Only CSV files are allowed.',
    csv_file_too_large: 'File size exceeds 5MB. Please use a smaller file.',
    csv_read_error: 'Failed to read CSV file. Please check the file format.',
    csv_max_rows: 'CSV exceeds 1000 rows limit. Please split the file.',
    csv_missing_columns: 'Please map the required columns (Date & Item).',
    csv_no_data: 'No valid data found in CSV.',
    csv_ai_error: 'AI processing failed',
    csv_import_failed: 'Import failed',
    csv_upload_title: 'Upload your CSV file',
    csv_format_example: '📋 CSV Format Example Table',
    csv_format_hint: '** group & category columns are optional — AI will auto-assign **',
    csv_col_mapping: 'Column Mapping',
    csv_rows: 'rows',
    csv_col_date: 'Date',
    csv_col_item: 'Item / Description',
    csv_col_category: 'Category',
    csv_col_group: 'Group (optional — AI assigns)',
    csv_amount_format: 'Amount Column Format',
    csv_split_columns: 'Separate Income/Expense',
    csv_single_column: 'Single Amount Column',
    csv_col_income: 'Income Column',
    csv_col_expense: 'Expense Column',
    csv_col_amount: 'Amount Column',
    csv_col_type: 'Type Column',
    csv_default_type: 'Default Type',
    csv_default_group: 'Default Group (fallback)',
    csv_default_category: 'Default Category (fallback)',
    csv_ai_toggle: 'AI Auto Group & Category',
    csv_preview_with_ai: 'Preview with AI →',
    csv_preview_btn: 'Preview →',
    csv_processing: 'Processing...',
    csv_preview_title: 'Preview',
    csv_preview_showing: 'entries · showing first 5',
    csv_more_entries: 'more entries',
    csv_import_btn: 'Import {count} entries',
    csv_importing: 'Importing...',
    csv_cancel: 'Cancel',
    csv_back: '← Back',
    csv_done_title: 'Import Complete!',
    csv_import_more: 'Import More',
    csv_premium_title: 'Premium Feature',
    csv_premium_desc: 'This feature is available for Premium users only.',
    csv_select_col: '— Select —',

    // PremiumPackage
    premium_pkg_title: '👑 Premium Package',
    premium_pkg_features_header: 'Features',
    premium_pkg_free_col: 'Free',
    premium_pkg_pro_col: '👑 Pro',
    premium_pkg_choose_plan: 'Choose Plan',
    premium_pkg_payment_method: 'Payment Method',
    premium_pkg_monthly_label: '30 Days',
    premium_pkg_monthly_price: '8,000',
    premium_pkg_monthly_unit: 'MMK / 30 days',
    premium_pkg_yearly_label: '365 Days',
    premium_pkg_yearly_price: '60,000',
    premium_pkg_yearly_unit: 'MMK / yr',
    premium_pkg_yearly_badge: 'Save 39%',
    premium_pkg_copy_btn: 'Copy',
    premium_pkg_copied: '✓',
    premium_pkg_txn_label: 'Transaction ID',
    premium_pkg_txn_required: '*',
    premium_pkg_txn_placeholder: 'Enter your transaction ID...',
    premium_pkg_screenshot_label: 'Payment Screenshot',
    premium_pkg_screenshot_upload: 'Upload payment screenshot',
    premium_pkg_validation_txn: 'Transaction ID လိုပါသည်',
    premium_pkg_validation_screenshot: 'Screenshot တင်ပါ',
    premium_pkg_submit_btn: '✨ Submit Payment',
    premium_pkg_submitting: 'Submitting...',
    premium_pkg_footer: 'Admin will verify and activate within 24 hours',
    premium_pkg_success_title: 'Payment Submitted!',
    premium_pkg_success_desc: 'Admin review in progress. Account activation usually takes less than 24 hours.',
    premium_pkg_back_btn: 'Back',
    premium_pkg_feature_receipt: 'Receipt Scan & AI Analyze',
    premium_pkg_feature_csv: 'CSV File Import',
    premium_pkg_feature_autopay: 'Auto Payments',
    premium_pkg_feature_backup: 'Backup & Restore',
    premium_pkg_feature_notion: 'Notion Sync',
    premium_pkg_feature_support: 'Priority Support',
    premium_pkg_feature_manual: 'Manual Entry',
    premium_pkg_feature_dashboard: 'Dashboard & Charts',
    premium_pkg_feature_export: 'Export (CSV/Excel/PDF)',

    // Admin Panel tabs & buttons
    admin_tab_users: 'Users',
    admin_tab_payments: 'Payments',
    admin_manage_btn: 'Manage',
    admin_entries_count: 'entries',
    admin_user_updated_toast: 'User updated ✓',
    admin_refresh_btn: 'Refresh',
    admin_loading: 'Loading...',
    admin_critical_zone: 'Critical Zone',
    admin_session_footer: 'Administrative Session',
    admin_add_days_hint: 'Add (+30) · Subtract (-3) · Calculated from current expiry',

    // Payment statuses & filters
    payment_status_pending: 'Pending',
    payment_status_approved: 'Approved',
    payment_status_rejected: 'Rejected',
    payment_filter_all: 'All',
    payment_search_placeholder: 'Search by email or transaction ID...',
    payment_no_results: 'No payment requests found',
    payment_screenshot_label: 'Payment Screenshot',
    payment_txn_id_label: 'Transaction ID',
    payment_full_details_label: 'Full Details',
    payment_approve_btn: 'Approve',
    payment_undo_warning: "This will also revert the user's Premium role.",
    payment_reject_modal_title: 'Reject Payment',

    // Premium package new keys
    premium_pkg_days: 'days',
    premium_pkg_currency: 'MMK',
    premium_pkg_per_day: 'MMK/day',
    premium_pkg_badge_popular: '🔥 Popular',
    premium_pkg_badge_best: '⭐ Best Value',

    // Notification
    notification_tap_to_read: 'Tap to read more',

    // Premium visibility
    premium_renew_desc: 'Extend or renew your Premium subscription',
    premium_unlock_desc: 'Unlock all premium features',

    // Days subtracted toast
    toast_days_subtracted: '{days} days subtracted.',
  },

  my: {
    // Bottom Nav
    nav_home: 'ပင်မ',
    nav_dashboard: 'ဒက်ရှ်ဘုတ်',
    nav_budget: 'ဘတ်ဂျက်',
    nav_transactions: 'စာရင်း',
    nav_profile: 'ပရိုဖိုင်',
    // Settings Menu
    settings_title: 'ဆက်တင်',
    settings_admin_panel: 'အက်ဒမင်',
    settings_api_credentials: 'သိမ်းဆည်းမှု & API',
    settings_notion_guide: 'Notion လမ်းညွှန်',
    settings_customize: 'အုပ်စုနှင့်ကဏ္ဍများ',
    settings_history: 'မှတ်တမ်း',
    settings_auto_payments: 'အလိုအလျောက် ငွေပေးချေမှု',
    settings_backup: 'Backup & ပြန်လည်ရယူရန်',
    settings_contact: 'ဆက်သွယ်ရန်',
    settings_language: 'ဘာသာစကား',
    // Auth
    auth_sign_in: 'အကောင့်ဝင်မည်',
    auth_sign_up: 'အကောင့်ဖွင့်မည်',
    auth_sign_out: 'အကောင့်ထွက်မည်',
    auth_email: 'Email',
    auth_password: 'စကားဝှက်',
    auth_forgot_password: 'စကားဝှက် မမှတ်မိပါ',
    auth_reset_password: 'စကားဝှက် ပြန်လည်သတ်မှတ်ပါ',
    auth_confirm_password: 'စကားဝှက် အတည်ပြုပါ',
    auth_new_password: 'စကားဝှက် အသစ်',
    auth_signup_success: 'စာရင်းသွင်းပြီးပါပြီ။ Email ကို စစ်ဆေးပြီးအတည်ပြုပေးပါ။',
    auth_signin_success: 'အကောင့်ဝင်ရောက်ပြီးပါပြီ။',
    auth_reset_email_sent: 'စကားဝှက် ပြန်လည်သတ်မှတ်ရန် Email ပို့ပြီးပါပြီ။',
    auth_password_changed: 'စကားဝှက် ပြောင်းလဲပြီးပါပြီ။ ပြန်လည်ဝင်ရောက်ပေးပါ။',
    auth_password_mismatch: 'စကားဝှက် တူညီမှု မရှိပါ။ ပြန်စစ်ဆေးပါ။',
    auth_password_too_short: 'စကားဝှက် အနည်းဆုံး ၆ လုံး ရှိရမည်။',
    // Buttons
    btn_save: 'သိမ်းဆည်းမည်',
    btn_delete: 'ဖျက်မည်',
    btn_cancel: 'မလုပ်တော့ပါ',
    btn_confirm: 'အတည်ပြုမည်',
    btn_close: 'ပိတ်မည်',
    btn_edit: 'ပြင်ဆင်မည်',
    btn_add: 'ထည့်သွင်းမည်',
    btn_send: 'ပို့မည်',
    btn_load_more: 'ထပ်တင်မည် ({count} ကျန်သည်)',
    btn_got_it: 'နားလည်ပါပြီ',

    btn_backup_now: 'ယခု Backup လုပ်မည်',
    btn_restore: 'ပြန်လည်ထားရမည်',
    btn_replace: 'အစားထိုးမည်',
    btn_merge: 'ပေါင်းထည့်မည်',
    // Dashboard
    dashboard_title: 'ဒက်ရှ်ဘုတ်',
    dashboard_overview: 'အနှစ်ချုပ်',
    dashboard_income: 'ဝင်ငွေ',
    dashboard_expense: 'အသုံးစရိတ်',
    dashboard_balance: 'လက်ကျန်ငွေ',
    dashboard_by_group: 'အုပ်စုအလိုက်',
    dashboard_monthly_trend: 'အသုံးများဆုံးစာရင်း',
    dashboard_expense_by_group: 'အုပ်စုအလိုက် အသုံးစရိတ်',
    dashboard_current: 'လက်ရှိ',
    dashboard_tap_to_view: 'အသေးစိတ်ကြည့်ရန် နှိပ်ပါ',
    dashboard_of_budget: 'ဘတ်ဂျက်၏',
    dashboard_no_budget_set: 'ဘတ်ဂျက် မသတ်မှတ်ရသေးပါ',
    dashboard_left: 'ကျန်သည်',
    // Home / Input
    input_placeholder: 'ဝင်ငွေ သို့မဟုတ် အသုံးစရိတ် ရိုက်ထည့်ပါ...',
    input_listening: 'နားထောင်နေပါသည်...',
    input_ai_parsing: 'AI စစ်ဆေးနေပါသည်...',
    input_required: 'စာသား သို့မဟုတ် ပုံ တစ်ခုခု ထည့်သွင်းပေးပါ။',
    input_ai_success: 'AI စစ်ဆေးမှု အောင်မြင်ပါသည်။',
    input_send_to_notion: 'Notion သို့ ပို့မည်',
    input_save_to_app: 'App တွင် သိမ်းမည်',
    // Parsed Entries
    parsed_empty: 'မှတ်တမ်း မရှိသေးပါ။',
    parsed_item: 'အကြောင်းအရာ',
    parsed_group: 'အုပ်စု',
    parsed_category: 'ကဏ္ဍ',
    parsed_date: 'ရက်စွဲ',
    parsed_amount: 'ပမာဏ',
    parsed_type: 'အမျိုးအစား',
    // Toast
    toast_entry_saved: 'မှတ်တမ်း သိမ်းဆည်းပြီးပါပြီ။',
    toast_entries_saved: 'မှတ်တမ်း {count} ခု သိမ်းဆည်းပြီးပါပြီ။',
    toast_entry_deleted: 'မှတ်တမ်း ဖျက်ပြီးပါပြီ။',
    toast_entries_deleted: 'မှတ်တမ်း {count} ခု ဖျက်ပြီးပါပြီ။',
    toast_entry_updated: 'မှတ်တမ်း ပြင်ဆင်ပြီးပါပြီ။',
    toast_budget_exceeded: '⚠ {group} ဘတ်ဂျက် ကျော်လွန်သွားပါပြီ! ({spent} / {limit})',
    toast_notion_all_success: 'Notion သို့ မှတ်တမ်း {count} ခု အကုန် ပို့ပြီးပါပြီ။',
    toast_notion_partial: '{success} ခု အောင်မြင်သည်၊ {failed} ခု မအောင်မြင်ပါ။',
    toast_notion_all_failed: 'မှတ်တမ်းများပို့ခြင်း မအောင်မြင်ပါ။',
    toast_notion_missing: 'Notion API Key သို့မဟုတ် Database ID လိုအပ်ပါသည်။ ဆက်တင်တွင် ဖြည့်ပေးပါ။',
    toast_settings_saved: 'ဆက်တင်များကို Cloud တွင် သိမ်းဆည်းပြီးပါပြီ။',
    toast_settings_load_failed: 'ဆက်တင် ဆွဲယူမအောင်မြင်ပါ။',
    toast_budget_saved: '{group} ဘတ်ဂျက် သိမ်းဆည်းပြီးပါပြီ။',
    toast_budget_save_failed: 'ဘတ်ဂျက် သိမ်းဆည်းမအောင်မြင်ပါ။',
    toast_budget_deleted: '{group} ဘတ်ဂျက် ဖျက်ပြီးပါပြီ။',
    toast_budget_delete_failed: 'ဘတ်ဂျက် ဖျက်မအောင်မြင်ပါ။',
    toast_backup_load_failed: 'Backup စာရင်း ဆွဲယူမအောင်မြင်ပါ။',
    toast_backup_failed: 'Backup မအောင်မြင်ပါ။',
    toast_backup_saved: 'Backup သိမ်းဆည်းပြီးပါပြီ။ (မှတ်တမ်း {count} ခု)',
    toast_restore_failed: 'Restore မအောင်မြင်ပါ။',
    toast_restore_success: 'Restore အောင်မြင်ပါသည်။ (မှတ်တမ်း {count} ခု)',
    toast_backup_deleted: 'Backup ဖျက်ပြီးပါပြီ။',
    toast_backup_delete_failed: 'Backup ဖျက်မအောင်မြင်ပါ။',
    toast_role_changed: 'Role ကို {role} သို့ ပြောင်းပြီးပါပြီ။',
    toast_account_deleted: '{email} ၏ အကောင့် ဖျက်ပြီးပါပြီ။',
    // Errors
    error_gemini_quota: 'Gemini API အသုံးပြုမှု ပမာဏ ပြည့်သွားပါပြီ။ ခေတ္တစောင့်ပြီး ပြန်ကြိုးစားပါ။',
    error_gemini_invalid_key: 'Gemini API Key မှားယွင်းနေပါသည်။ ဆက်တင်တွင် ပြန်စစ်ဆေးပါ။',
    error_server_busy: 'Server အလုပ်များနေသည်။ ခေတ္တစောင့်ပြီး ပြန်ကြိုးစားပါ။',
    error_content_blocked: 'ဤအကြောင်းအရာကို စစ်ဆေး၍ မရပါ။ အခြားစာသားဖြင့် စမ်းကြည့်ပါ။',
    error_notion_invalid_key: 'Notion API Key မှားယွင်းနေပါသည်။ ဆက်တင်တွင် Integration Token ပြန်စစ်ဆေးပါ။',
    error_notion_db_not_found: 'Notion Database ကို ရှာမတွေ့ပါ။ Database ID နှင့် Integration ချိတ်ဆက်မှု စစ်ဆေးပါ။',
    error_notion_no_access: 'Integration မှ ဤ Database ကို ဖတ်ခွင့် မရှိပါ။ Database → Share → Integration ထည့်ပေးပါ။',
    error_notion_validation: 'Notion Column အမည်များ မှားယွင်းနေပါသည်။ လိုအပ်သည်: Date, Item, Group, Category, Income, Expense။',
    error_unauthorized: 'ချိတ်ဆက်မှု ခွင့်ပြုချက် မရှိပါ။ API Key သို့မဟုတ် Token သက်တမ်း ကုန်နေနိုင်သည်။',
    error_invalid_credentials: 'Email သို့မဟုတ် Password မှားယွင်းနေပါသည်။',
    error_user_registered: 'ဤ Email ဖြင့် အကောင့် ရှိပြီးသားဖြစ်သည်။',
    error_email_not_confirmed: 'Email အတည်ပြုရန် လိုအပ်ပါသည်။ Email ကိုစစ်ကာ အတည်ပြုပေးပါ။',
    error_session_expired: 'Session သက်တမ်း ကုန်သွားပါပြီ။ ပြန်လည်ဝင်ရောက်ပေးပါ။',
    error_network: 'အင်တာနက် ချိတ်ဆက်မှု မကောင်းပါ။',
    error_timeout: 'ချိတ်ဆက်မှု အချိန်ကုန်သွားပါပြီ။ ပြန်ကြိုးစားပါ။',
    error_image_too_large: 'ပုံ၏ အရွယ်အစား 3MB ကျော်နေပါသည်။ ပုံအရွယ်အစား လျှော့ချပေးပါ။',
    error_unexpected: 'ပြန်ကြိုးစားပါ။',
    // Approval Popup
    // History
    history_title: 'မှတ်တမ်း',
    history_search_placeholder: 'ရှာဖွေမည်...',
    history_empty: 'မှတ်တမ်း မရှိသေးပါ။',
    history_delete_confirm: 'မှတ်တမ်း {count} ခု ဖျက်မည်မှာ သေချာပါသလား?',
    history_entry_deleted: 'မှတ်တမ်း ဖျက်ပြီးပါပြီ။',
    // Backup
    backup_count: 'Backup {count} ခု သိမ်းထားသည်',
    backup_empty: 'Backup မရှိသေးပါ။',
    backup_empty_hint: '"ယခု Backup လုပ်မည်" နှိပ်ပြီး သိမ်းပါ။',
    backup_merge_hint: '✦ လက်ရှိ မှတ်တမ်းများ ထားပြီး Backup မှတ်တမ်းများ ထပ်ထည့်မည်။',
    backup_replace_hint: '⚠️ လက်ရှိ မှတ်တမ်းများ အကုန် ဖျက်ပြီး Backup ဖြင့် အစားထိုးမည်။',
    backup_delete_confirm: 'ဤ Backup ကို ဖျက်မည်မှာ သေချာပါသလား?',
    backup_replace_confirm: 'Replace Restore လုပ်မည်မှာ သေချာပါသလား?',
    backup_merge_confirm: 'Merge Restore လုပ်မည်မှာ သေချာပါသလား?',
    backup_delete_warning: 'ဤ Backup ကို ပြန်မရအောင် ဖျက်မည်။',
    backup_replace_warning: 'လက်ရှိ မှတ်တမ်းများ အကုန် ဖျက်မည်။',
    backup_merge_desc: 'Backup မှ မှတ်တမ်း {count} ခုကို လက်ရှိ data နှင့် ပေါင်းထည့်မည်။',
    backup_replace_desc: 'Backup မှ မှတ်တမ်း {count} ခု ပြန်ထည့်မည်။',
    // Admin
    admin_title: 'အက်ဒမင်',
    admin_delete_confirm: '"{email}" ၏ အကောင့်နှင့် data အကုန် ဖျက်မည်။ ပြန်လည်မရရှိနိုင်ပါ။',
    admin_promote: 'Admin အဖြစ် တိုးမြှင့်မည်',
    admin_demote: 'Admin ပယ်ဖျက်မည်',
    // Voice
    voice_not_supported: 'ဤ browser တွင် အသံမှတ်မိမှု အသုံးမပြုနိုင်ပါ။',
    voice_no_speech: 'အသံ မရရှိပါ။ ပြန်ကြိုးစားပါ။',
    voice_no_speech_timeout: 'အသံ ၅ စက္ကန့် မရရှိ၍ အလိုအလျောက် ရပ်သွားပါပြီ။',
    voice_mic_denied: 'Microphone ခွင့်ပြုချက် မရှိပါ။ Browser ဆက်တင်တွင် ခွင့်ပြုပေးပါ။',
    voice_failed: 'အသံမှတ်မိမှု မအောင်မြင်ပါ။',
    // Profile
    profile_title: 'ပရိုဖိုင်',
    profile_email: 'Email',
    profile_role: 'အခန်းကဏ္ဍ',
    profile_member_since: 'အဖွဲ့ဝင်ခဲ့သည်မှာ',
    profile_app_version: 'App ဗားရှင်း',
    // Misc
    api_credentials_required: 'API အချက်အလက်များ လိုအပ်ပါသည်',
    api_credentials_desc: 'Gemini Key, Notion Key နှင့် Database ID တို့ကို ဆက်တင်တွင် ဖြည့်ပေးပါ။',
    confirm_delete_entry: '"{item}" ကို ဖျက်မှာ သေချာပါသလား',
    error_occurred: 'အမှားတစ်ခု ဖြစ်ပွားပါသည်',
    loading: 'ဆွဲယူနေပါသည်...',
    saving: 'သိမ်းဆည်းနေပါသည်...',
    no_data: 'ဒေတာ မရှိသေးပါ။',
    optional: 'ရွေးချယ်နိုင်သည်',
    required: 'လိုအပ်သည်',

    // --- Dashboard extra ---
    dashboard_entries: 'ဝင်မှတ်တမ်း',
    dashboard_summary: 'အနှစ်ချုပ်',
    dashboard_over_by: 'လွန်သည်',
    dashboard_saving_rate: 'စုဆောင်းနှုန်း',
    dashboard_monthly_overview: 'လစဥ်အနှစ်ချုပ်',
    dashboard_top_categories: 'ထိပ်ဆုံး ခေါင်းစဥ်များ',
    dashboard_year_income: 'နှစ်ချုပ် ဝင်ငွေ',
    dashboard_year_expense: 'နှစ်ချုပ် အသုံးစရိတ်',
    // --- DataTable ---
    col_item_date: 'ပစ္စည်း / ရက်စွဲ',
    col_amount: 'ပမာဏ',
    col_category: 'အမျိုးအစား',
    col_category_group: 'အမျိုးအစား / အုပ်စု',
    table_header_entries: 'မှတ်တမ်း',
    filter_year: 'နှစ်',
    filter_month: 'လ',
    filter_type: 'အမျိုးအစား',
    filter_group: 'အုပ်စု',
    filter_category: 'ခေါင်းစဥ်',
    filter_income: 'ဝင်ငွေ',
    filter_expense: 'အသုံးစရိတ်',
    filter_all: 'အားလုံး',
    btn_clear_filters: 'စစ်ထုတ်မှု ရှင်းပါ',
    export_rows: '{count} ကြောင်း ထုတ်မည်',
    search_placeholder: 'ရှာဖွေရန်...',
    no_entries_found: 'မှတ်တမ်း မတွေ့ပါ',
    delete_entry_title: 'မှတ်တမ်း ဖျက်မည်',
    delete_entry_desc: '"{item}" ကို ဖျက်မည်လား?',
    parsed_title: 'ခွဲခြမ်းစိတ်ဖြာ ရလဒ်',
    parsed_tap_to_edit: 'နှိပ်ပြင်ရန်',
    parsed_send_to_notion: 'Notion သို့ ပေးပို့မည်',
    parsed_save_entries: 'သိမ်းဆည်းမည်',
    input_welcome: 'ပြန်လာပြီနော်! ဒီနေ့ ဘာတွေသုံးခဲ့လဲ?',
    input_upload_prompt: 'ဓာတ်ပုံ တင်ရန် နှိပ်ပါ',
    input_upload_hint: 'JPG၊ PNG — 3MB အထိ',
    input_parse_btn: 'ခွဲခြမ်းပါ',
    profile_preferences: 'ဦးစားပေးချက်များ',
    profile_account_security: 'အကောင့် & လုံခြုံရေး',
    profile_storage_mode: 'သိမ်းဆည်းနည်း',
    profile_storage_hint: 'ဒေတာ သိမ်းဆည်းသည့် နေရာ',
    profile_app_only: 'App ထဲသာ',
    profile_notion_sync: 'Notion Sync',
    profile_joined: 'ထည့်သွင်းသည်',
    profile_add_display_name: '+ နာမည် ထည့်ရန်',
    profile_display_name_placeholder: 'ပြသည့်နာမည်',
    profile_theme_current: '{mode} မြင်ကွင်း',
    profile_dark_mode: 'အမည်းနောက်ခံ',
    profile_light_mode: 'အဖြူနောက်ခံ',
    profile_change_password: 'စကားဝှက် ပြောင်းရန်',
    profile_new_password: 'စကားဝှက် အသစ်',
    profile_confirm_password: 'စကားဝှက် အတည်ပြုရန်',
    profile_delete_account: 'အကောင့် ဖျက်ရန်',
    profile_notion_requires: 'Notion Sync သည် Premium သို့ Admin လိုအပ်သည်။',
    entry_add_title: 'မှတ်တမ်း ထည့်ရန်',
    entry_edit_title: 'မှတ်တမ်း ပြင်ရန်',
    entry_add_new: 'အသစ် ထည့်ရန်',
    entry_item_name: 'အရာ နာမည်',
    entry_amount: 'ပမာဏ',
    entry_date: 'ရက်စွဲ',
    entry_group: 'အုပ်စု',
    entry_category: 'အမျိုးအစား',
    entry_save: 'သိမ်းရန်',
    entry_select_group: 'အုပ်စု ရွေးပါ',
    entry_select_category: 'အမျိုးအစား ရွေးပါ',
    entry_group_name_placeholder: 'အုပ်စုနာမည်',
    entry_category_name_placeholder: 'ခေါင်းစဥ်နာမည်',
    entry_picker_group: 'အုပ်စု',
    entry_picker_category: 'အမျိုးအစား',
    contact_desc: 'အကူအညီ လိုသလား? အောက်ပါ လင့်ခ်များမှ ဆက်သွယ်ပါ။',
    budget_tab_limits: 'ဘတ်ဂျက် သတ်မှတ်ချက်',
    budget_tab_allocation: 'ခွဲဝေမှုဇယား',
    budget_group_limits: 'အုပ်စုဘတ်ဂျက် သတ်မှတ်ချက်',
    budget_total: 'စုစုပေါင်း',
    budget_spent: 'သုံးပြီး',
    budget_used: 'သုံးပြီး',
    budget_over_by: 'လွန်ကဲနေသည်',
    budget_no_limit: 'သတ်မှတ်ချက် မရှိ',
    budget_allocation_balance: 'မခွဲဝေရသေးသော',
    budget_limit_help: 'Group များကို Setting ထဲတွင် စိတ်ကြိုက်ပြင်ဆင်နိုင်ပါသည်',
    api_keys_title: 'API သော့များ',
    api_app_desc: 'App Only မုဒ် — Gemini သော့ လိုအပ်သည်။',
    autopay_empty: 'အလိုအလျောက် ငွေပေးချေမှု မရှိသေးပါ။',
    autopay_new_title: 'အသစ် ထည့်ရန်',
    autopay_edit_title: 'ပြင်ဆင်ရန်',
    autopay_btn_add: 'ငွေပေးချေမှု ထည့်ရန်',
    autopay_premium_only: 'Auto Payments သည် Premium အင်္ဂါရပ်ဖြစ်သည်။',
    autopay_active_info: 'အသုံးပြုချိန်တွင် အလိုအလျောက် လည်ပတ်သည်။',
    btn_run_now: 'ယခု လည်ပတ်ရန်',
    btn_save_changes: 'ပြောင်းလဲမှု သိမ်းရန်',
    btn_save_settings: 'ဆက်တင် သိမ်းရန်',
    premium_feature: 'Premium အင်္ဂါရပ်',
    scan_premium_desc: 'ဘောင်ချာ scan လုပ်ခြင်းသည် Premium သုံးစွဲသူများသာ ရနိုင်ပါသည်။',
    deleting: 'ဖျက်နေသည်...',
    saved: 'သိမ်းပြီး',
    toast_name_updated: 'နာမည် ပြောင်းပြီးပါပြီ။',
    toast_name_failed: 'နာမည် ပြောင်းမရပါ။',
    toast_avatar_updated: 'ရုပ်ပုံ ပြောင်းပြီးပါပြီ။',
    toast_avatar_failed: 'ရုပ်ပုံ ပြောင်းမရပါ။',
    toast_pw_too_short: 'စကားဝှက် ၆ လုံးအထက် ရှိရမည်။',
    toast_pw_mismatch: 'စကားဝှက်များ မတူညီပါ။',
    toast_pw_changed: 'စကားဝှက် ပြောင်းပြီးပါပြီ။',
    toast_pw_failed: 'စကားဝှက် ပြောင်းမရပါ။',
    toast_account_deleted_self: 'အကောင့် ဖျက်ပြီးပါပြီ။',
    toast_delete_failed: 'အကောင့် ဖျက်မရပါ။',
    toast_item_required: 'အမျိုးအစား ထည့်ရမည်။',
    toast_amount_required: 'ပမာဏ ထည့်ရမည်။',
    toast_save_failed: 'သိမ်းမရပါ။',
    toast_update_failed: 'ပြင်မရပါ။',
    toast_deleted: 'ဖျက်ပြီးပါပြီ။',
    toast_updated: 'ပြင်ဆင်ပြီးပါပြီ။',
    toast_autopay_added: 'အလိုအလျောက် ငွေပေးချေမှု ထည့်ပြီးပါပြီ။',
    notification_title: 'အကြောင်းကြားချက်များ',
    notification_mark_all: 'အားလုံးကို ဖတ်ပြီးကြောင်း မှတ်သားမည်',
    notification_empty: 'အကြောင်းကြားချက် မရှိသေးပါ။',
    notification_recent: 'နောက်ဆုံး အခြေအနေများ',
    toast_autopay_load_failed: 'ဒေတာ ရယူမရပါ။',
    toast_no_payments_due: 'ကြေးပေးဆပ်ရမည့် မှတ်တမ်း မရှိပါ။',
    toast_run_failed: 'ပေးချေမှု မအောင်မြင်ပါ။',
    profile_mode_dark: 'အမှောင်',
    profile_mode_light: 'အလင်း',
    auth_no_account: 'အကောင့် မရှိသေးဘူးလား? အကောင့်ဖွင့်မည်',
    auth_have_account: 'အကောင့် ရှိပြီးသားလား? အကောင့်ဝင်မည်',
    tab_text: 'စာသား',
    tab_scan: 'စကန် ဓာတ်ပုံ',
    tab_file: 'ဖိုင်',
    home_recent_activity: 'မကြာမီ မှတ်တမ်းများ',
    home_see_all: 'အားလုံးကြည့်',
    budget_group_limits_label: 'အုပ်စု ဘတ်ဂျက် သတ်မှတ်ချက်',
    settings_backup_restore: 'Backup & Restore',
    auth_subtitle: 'သင့်ကိုယ်ပိုင် ငွေစာရင်း မှတ်သားရာနေရာ။',
    auth_app_name: 'Notion-Ex Tracker',
    auth_username: 'အမည်',
    auth_username_placeholder: 'အသုံးပြုမည့်အမည်',
    auth_email_label: 'Email လိပ်စာ',
    auth_email_placeholder: 'you@example.com',
    auth_password_label: 'စကားဝှက်',
    auth_or_continue: 'သို့မဟုတ် ဆက်လက်လုပ်ဆောင်မည်',
    auth_create_account: 'အကောင့်ဖွင့်မည်',
    auth_forgot_link: 'စကားဝှက် မမှတ်မိ?',
    auth_send_reset: 'Reset Link ပို့မည်',
    auth_back_to_signin: 'အကောင့်ဝင်ရာသို့ ပြန်သွားမည်',
    auth_reset_enter_email: 'Email ထည့်ပါ၊ Reset Link ပို့ပေးပါမည်။',
    auth_check_email_title: 'Email စစ်ဆေးပါ 📬',
    auth_check_email_body: '{email} သို့ Reset Link ပို့ပြီးပါပြီ။ Link ကိုနှိပ်၍ စကားဝှက် ပြောင်းပါ။',
    auth_spam_hint: 'မတွေ့ပါက Spam folder စစ်ဆေးပါ။',
    auth_set_new_password: 'စကားဝှက် အသစ် သတ်မှတ်ပါ',
    auth_new_password_placeholder: 'အနည်းဆုံး ၆ လုံး',
    auth_confirm_password_label: 'စကားဝှက် အတည်ပြုပါ',
    auth_confirm_password_placeholder: 'စကားဝှက် ထပ်ထည့်ပါ',
    auth_passwords_no_match: 'စကားဝှက် တူညီမှု မရှိပါ',

    dashboard_app_only: 'Dashboard သည် App Only မုဒ်တွင်သာ ကြည့်ရှုနိုင်ပါသည်။',
    dashboard_entries_count: 'မှတ်တမ်း ({count})',

    // Home / App header
    home_tagline: 'Notion-Ex ဖြင့် ပိုမိုထိရောက်သော ငွေစာရင်းမှတ်တမ်း',

    // App.tsx & BudgetSettings
    toast_autopay_triggered: 'အလိုအလျောက် ထည့်သွင်းပြီး: {items}',
    budget_limit_placeholder: 'ဘတ်ဂျက် ဖျက်ရန် ဗလာထားပါ',

    // Camera / Gallery
    input_gallery_btn: 'ပြခန်း',
    input_camera_btn: 'ကင်မရာ',
    camera_capture_title: 'ဓာတ်ပုံရိုက်',

    // AuthForm toast messages
    toast_username_required: 'Username ထည့်ပါ။',
    toast_signup_success: 'အကောင့်ဖွင့်ပြီးပါပြီ! Email စစ်ဆေးပါ။',
    toast_signin_success: 'ဝင်ရောက်မှု အောင်မြင်ပါသည်!',
    toast_pw_reset_sent: 'စကားဝှက် ပြင်ဆင်ရန် Email ပို့ပြီးပါပြီ!',
    toast_pw_changed_signin: 'စကားဝှက် ပြောင်းပြီးပါပြီ။ ပြန်လည်ဝင်ပါ။',
    toast_pw_mismatch_check: 'စကားဝှက်များ မတူညီပါ။ ပြန်စစ်ပါ။',
    auth_update_password: 'စကားဝှက် အပ်ဒိတ်မည်',

    // NotionGuide
    notion_guide_banner_title: 'Notion Sync သုံးရန် Premium လိုအပ်သည်',
    notion_guide_banner_desc: 'Notion Sync သည် Premium သုံးစွဲသူများအတွက်သာ ရနိုင်သည်။ Notion database နှင့် sync လုပ်ရန် Premium သို့ အဆင့်မြှင့်ပါ။',
    notion_guide_banner_btn: '👑 Premium သို့ အဆင့်မြှင့်မည်',
    notion_guide_divider: 'Notion ဘယ်လိုတပ်ဆင်မလဲ',
    notion_guide_template_title: 'Notion Template',
    notion_guide_template_subtitle: 'Workspace သို့ Download & Duplicate လုပ်ပါ',
    notion_guide_template_open: 'ဖွင့်မည်',
    notion_guide_steps_label: 'တပ်ဆင်ရေး အဆင့်ဆင့် လမ်းညွှန်',
    notion_step1_title: 'Notion Template ကူးယူပါ',
    notion_step1_li1: 'အပေါ်က "Copy Notion Template" ခလုတ်ကို နှိပ်ပါ',
    notion_step1_li2: 'Notion page ပွင့်လာမည် — ညာဘက်အပေါ်ထောင့်မှ Duplicate ကို နှိပ်ပါ',
    notion_step1_li3: 'Database တစ်ခု သင့် Notion workspace ထဲသို့ ကူးယူမည်',
    notion_step1_tip: 'Column ၆ ခု ပါဝင်မည် — Date, Item, Income, Expense, Group, Category',
    notion_step2_title: 'Notion Integration ဖန်တီးပါ',
    notion_step2_li1: 'Browser မှ notion.so/profile/integrations သို့ သွားပါ',
    notion_step2_li2: 'New integration ခလုတ်ကို နှိပ်ပါ',
    notion_step2_li3: 'နာမည်ထည့်ပါ (ဉပမာ — Ex Tracker)',
    notion_step2_li4: 'Workspace ရွေးချယ်ပြီး Save ကို နှိပ်ပါ',
    notion_step2_li5: 'Internal Integration Secret (token) ကို ကူးယူပါ',
    notion_step2_tip: 'Token သည် ntn_ သို့မဟုတ် secret_ ဖြင့် စသည် — လျှို့ဝှက်ထားပါ',
    notion_step3_title: 'Database ကို Integration နဲ့ ချိတ်ဆက်ပါ',
    notion_step3_li1: 'ကူးယူထားသော Database page ကို ဖွင့်ပါ',
    notion_step3_li2: 'ညာဘက်အပေါ်ထောင့်မှ ••• (သုံးစက်) ကို နှိပ်ပါ',
    notion_step3_li3: 'Connections → Connect to ကို ရွေးပြီး Integration ကို ချိတ်ဆက်ပါ',
    notion_step3_tip: 'ဤအဆင့်ကို ကျော်လျှင် "permission denied" အမှားပေါ်မည်',
    notion_step4_title: 'Database ID ရှာပါ',
    notion_step4_li1: 'Browser မှ Database page ကို ဖွင့်ပါ',
    notion_step4_li2: 'URL ကို ကြည့်ပါ — အောက်ပါပုံစံဖြင့် ပေါ်မည်:',
    notion_step4_li3: '?v= မတိုင်မီ စိမ်းရောင်ဖြင့် ပြထားသော အက္ခရာ ၃၂ လုံးသည် Database ID ဖြစ်သည်',
    notion_step4_tip: 'URL တွင် / ပါက နောက်ဆုံး slash နောက်ပိုင်းကိုယူပါ',
    notion_step5_title: 'App ထဲ Key ထည့်ပါ',
    notion_step5_li1: 'Settings → API credentials သို့ သွားပါ',
    notion_step5_li2: 'Notion Integration Token တွင် Step 2 မှ token ကို ကူးထည့်ပါ',
    notion_step5_li3: 'Notion Database ID တွင် Step 4 မှ ID ကို ကူးထည့်ပါ',
    notion_step5_li4: 'Save နှိပ်ပါ — တပ်ဆင်မှု ပြီးပါပြီ! 🎉',
    notion_step5_tip: 'Save ပြီးနောက် entry တစ်ခု parse ကြည့်ပြီး Notion တွင် ပေါ်မပေါ်စစ်ပါ',

    // SettingsDrawer
    settings_history_title: 'မှတ်တမ်း',

    // AdminPanel
    admin_col_members: 'အဖွဲ့ဝင်',
    admin_col_premium: 'ပရီမီယံ',
    admin_col_admins: 'အက်မင်',
    admin_search_placeholder: 'အသုံးပြုသူ ရှာပါ...',
    admin_col_email: 'အီးမေးလ်',
    admin_col_status: 'အဆင့်အတန်း',
    admin_no_users: 'အသုံးပြုသူ မတွေ့ပါ',
    admin_badge_you: 'သင်',
    admin_status_active: '✓ တက်ကြွနေသည်',
    admin_user_info: 'အသုံးပြုသူ အချက်အလက်',
    admin_entries_label: 'မှတ်တမ်းများ',
    admin_last_active: 'နောက်ဆုံး ဝင်သည့်ရက်',
    admin_set_role: 'Role သတ်မှတ်ရန်',
    admin_delete_account_btn: 'အကောင့် ဖျက်မည်',
    admin_ban_btn: 'Ban / ပိတ်ဆို့မည်',
    admin_unban_btn: 'Ban ဖြုတ်မည်',
    admin_banned_badge: 'Ban ခံထား',
    admin_ban_confirm: '"{email}" ကို ban မည်လား? ထိုသူ ဝင်ရောက်၍ မရတော့ပါ။',
    admin_unban_confirm: '"{email}" ၏ ban ဖြုတ်မည်လား? ထိုသူ ပြန်ဝင်ရောက်နိုင်မည်။',
    admin_set_expiry: 'Premium သက်တမ်း သတ်မှတ်',
    admin_expiry_label: 'Premium သက်တမ်းကုန်ဆုံးရက်',
    admin_expiry_none: 'သက်တမ်းသတ်မှတ်မထား',
    admin_expiry_save: 'သိမ်းမည်',
    admin_expiry_clear: 'ရှင်းလင်းမည်',
    admin_manage_title: 'User စီမံမည်',
    admin_tab_general: 'အထွေထွေ',
    admin_tab_security: 'လုံခြုံရေး',
    admin_add_days_label: 'Premium ရက်ထပ်ဆက်မည်',
    admin_add_days_btn: 'ရက်ထည့်မည်',
    admin_reset_plan_btn: 'Free သို့ ပြန်ညှိမည်',
    admin_reset_plan_confirm: 'ဤ user ကို Free plan သို့ ပြန်ညှိမည်လား?',
    admin_send_reset_email: 'Password Reset ပို့မည်',
    admin_status_control: 'Status ထိန်းချုပ်မှု',
    toast_days_added: '{days} ရက် ထပ်ထည့်ပြီးပါပြီ။',
    toast_plan_reset: 'Plan ကို Free သို့ ပြန်ညှိပြီးပါပြီ။',
    toast_reset_email_sent: 'Password reset email ပို့ပြီးပါပြီ။',
    toast_user_banned: '{email} ကို ban ပြီးပါပြီ။',
    toast_user_unbanned: '{email} ၏ ban ဖြုတ်ပြီးပါပြီ။',
    toast_expiry_saved: 'Premium သက်တမ်း သိမ်းပြီးပါပြီ။',
    toast_expiry_cleared: 'Premium သက်တမ်း ရှင်းလင်းပြီးပါပြီ။',
    toast_premium_updated: 'Premium သက်တမ်း ပြင်ဆင်ပြီးပါပြီ။',
    toast_payment_approved: 'ငွေပေးချေမှု အတည်ပြုပြီးပါပြီ။',
    toast_payment_rejected: 'ငွေပေးချေမှု ငြင်းပယ်ပြီးပါပြီ။',
    toast_payment_undone: 'ငွေပေးချေမှု အခြေအနေကို Pending သို့ ပြန်ပြောင်းပြီးပါပြီ။',
    toast_password_reset_sent: 'Password reset email ပို့ပြီးပါပြီ။',
    payment_reject_reason_label: 'ငြင်းပယ်ရသော အကြောင်းရင်း (ရွေးချယ်နိုင်)',
    payment_reject_reason_placeholder: 'ဥပမာ - Transaction ID မမှန်ကန်ပါ၊ screenshot မရှင်းလင်းပါ...',
    payment_reject_btn: 'ငြင်းပယ်မည်',
    payment_undo_btn: 'ပြန်ဖြုတ်မည်',
    payment_undo_confirm: 'ဤ payment ကို pending ပြန်ပြောင်းမည်လား?',
    payment_details_label: 'အသေးစိတ်',
    payment_note_label: 'Admin မှတ်ချက်',

    // ApiSettings
    api_storage_mode_label: 'သိမ်းဆည်းမှု နည်းလမ်း',
    api_app_only_title: 'App ထဲသာ',
    api_app_no_notion: 'Notion မလိုပါ။',
    api_selected: 'ရွေးချယ်ပြီး ✓',
    api_notion_sync_title: 'Notion Sync',
    api_notion_sync_desc: 'Notion DB သို့ Sync လုပ်သည်။ API key လိုသည်။',
    api_premium_required: 'Premium သို့မဟုတ် Admin role လိုသည်။',
    api_keys_label: 'API Key များ',
    api_gemini_label: 'Gemini API Key',
    api_required_badge: 'လိုအပ်သည်',
    api_notion_key_label: 'Notion API Key',
    api_notion_credentials: 'Notion အထောက်အထားများ',
    api_database_id_label: 'Database ID',

    // HistorySettings
    history_sort_prefix: 'စီရင်ခြင်း:',
    history_delete_bulk_btn: 'ဖျက်မည်',
    history_select_all: 'အားလုံးရွေးမည်',
    history_deselect_all: 'အားလုံးဖယ်မည်',
    history_col_item_date: 'အကြောင်းအရာ / ရက်',
    history_col_category: 'အမျိုးအစား',
    history_col_amount: 'ငွေပမာဏ',
    history_sort_newest: 'အသစ်ဆုံး',
    history_sort_day: 'နေ့',
    history_sort_month: 'လ',
    history_sort_year: 'နှစ်',

    // AutoPayments
    autopay_header_title: 'အလိုအလျောက် ငွေပေးချေမှု',
    autopay_active_count: '{count} ခု တက်ကြွနေသည် · app ဖွင့်သောအခါ run သည်',
    autopay_run_now: 'ယခု Run မည်',
    autopay_add_btn: 'ထည့်မည်',
    autopay_item_label: 'ကုန်ပစ္စည်း/ဝန်ဆောင်မှု *',
    autopay_item_placeholder: 'ဉပမာ - အိမ်ငှားခ',
    autopay_amount_label: 'ငွေပမာဏ *',
    autopay_amount_placeholder: '40000',
    autopay_type_expense: '💸 အသုံးစရိတ်',
    autopay_type_income: '💰 ဝင်ငွေ',
    autopay_category_label: 'အမျိုးအစား',
    autopay_group_label: 'အုပ်စု',
    autopay_day_label: 'လ၏ ရက်နေ့ *',
    autopay_day_hint: 'တိုင်းတစ်လ',
    autopay_last_run: 'ပြီးခဲ့သည့် Run:',
    autopay_day_badge: 'ရက်',
    autopay_select_placeholder: '— ရွေးချယ်ပါ —',

    // CustomizeSettings
    customize_search_placeholder: '{label} ရှာပါ...',
    customize_type_placeholder: '{label} နာမည် ရိုက်ထည့်ပါ...',
    customize_add_btn: 'ထည့်မည်',
    customize_sort_az: 'A → Z',
    customize_sort_za: 'Z → A',
    customize_sort_default: 'မူလ',
    customize_no_items: '{label} မတွေ့ပါ',
    customize_save_btn: 'ပြောင်းလဲချက် သိမ်းမည်',
    customize_groups_tab: 'အုပ်စုများ',
    customize_categories_tab: 'အမျိုးအစားများ',

    // BackupRestore
    backup_premium_title: 'Premium အင်္ဂါရပ်',
    backup_premium_desc: 'Backup & Restore သည် Premium အသုံးပြုသူများအတွက်သာ ရနိုင်သည်။',
    backup_restore_mode_label: 'ပြန်လည်ရယူမှု နည်းလမ်း',
    backup_mode_merge: '🔀 ပေါင်းစည်းမည်',
    backup_mode_replace: '♻️ အစားထိုးမည်',
    backup_loading: 'ဖတ်နေသည်...',
    backup_entries_label: 'မှတ်တမ်းများ',

    // Profile roles & delete modal
    role_admin: 'Admin',
    role_premium: 'Premium',
    role_member: 'အဖွဲ့ဝင်',
    profile_delete_desc: 'သင့်မှတ်တမ်းများ၊ ဆက်တင်များနှင့် ဘတ်ဂျက်အားလုံးကို အပြီးအပိုင် ဖျက်သွားမည်။',
    profile_delete_type: '{word} ဟု ရိုက်ထည့်ပြီး အတည်ပြုပါ။',
    pull_to_refresh: 'ဆွဲ၍ ပြန်ဆွဲယူပါ',
    release_to_refresh: 'လွှတ်၍ ပြန်ဆွဲယူပါ',
    refreshing: 'ပြန်ဆွဲယူနေပါသည်...',
    feature_unavailable_title: 'အသုံးပြု၍ မရပါ',
    feature_unavailable_desc: 'ဤ အင်္ဂါရပ်သည် Notion Sync မုဒ်တွင် မရရှိနိုင်ပါ။ Profile တွင် App Only မုဒ်သို့ ပြောင်းပါ။',
    go_to_settings: 'ဆက်တင်သို့ သွားမည်',
    voice_input_title: 'အသံဖြင့် ထည့်သွင်းမည်',
    upload_photo_title: 'ဓာတ်ပုံ တင်မည်',
    voice_resume_title: 'ဆက်လုပ်မည်',
    voice_pause_title: 'ခေတ္တရပ်မည်',
    voice_stop_title: 'ရပ်မည်',

    // CSV Import
    csv_only_csv_allowed: 'CSV ဖိုင်များသာ တင်နိုင်ပါသည်။',
    csv_file_too_large: 'ဖိုင်အရွယ်အစား 5MB ကျော်နေပါသည်။ သေးငယ်သောဖိုင် သုံးပေးပါ။',
    csv_read_error: 'CSV ဖိုင် ဖတ်မရပါ။ ဖိုင်ပုံစံ စစ်ဆေးပေးပါ။',
    csv_max_rows: 'CSV တွင် row 1000 ကျော်နေပါသည်။ ဖိုင်ကို ခွဲပေးပါ။',
    csv_missing_columns: 'Date နှင့် Item column များ ရွေးချယ်ပေးပါ။',
    csv_no_data: 'CSV တွင် ဒေတာ မတွေ့ပါ။',
    csv_ai_error: 'AI စစ်ဆေးမှု မအောင်မြင်ပါ',
    csv_import_failed: 'Import မအောင်မြင်ပါ',
    csv_upload_title: 'CSV ဖိုင် တင်ပါ',
    csv_format_example: '📋 CSV ဖော်မတ် နမူနာ',
    csv_format_hint: '** group နှင့် category column များ မထည့်လည်း AI မှ အလိုအလျောက် သတ်မှတ်ပေးမည် **',
    csv_col_mapping: 'Column ချိတ်ဆက်မှု',
    csv_rows: 'ကြောင်း',
    csv_col_date: 'ရက်စွဲ',
    csv_col_item: 'အကြောင်းအရာ / ဖော်ပြချက်',
    csv_col_category: 'အမျိုးအစား',
    csv_col_group: 'အုပ်စု (မလိုအပ် — AI သတ်မှတ်မည်)',
    csv_amount_format: 'ငွေပမာဏ Column ပုံစံ',
    csv_split_columns: 'ဝင်ငွေ/အသုံးစရိတ် ခွဲထားသော Column',
    csv_single_column: 'ငွေပမာဏ Column တစ်ခုတည်း',
    csv_col_income: 'ဝင်ငွေ Column',
    csv_col_expense: 'အသုံးစရိတ် Column',
    csv_col_amount: 'ငွေပမာဏ Column',
    csv_col_type: 'အမျိုးအစား Column',
    csv_default_type: 'မူရင်း အမျိုးအစား',
    csv_default_group: 'မူရင်း အုပ်စု (fallback)',
    csv_default_category: 'မူရင်း အမျိုးအစား (fallback)',
    csv_ai_toggle: 'AI မှ အုပ်စု & အမျိုးအစား သတ်မှတ်မည်',
    csv_preview_with_ai: 'AI ဖြင့် ကြိုကြည့်မည် →',
    csv_preview_btn: 'ကြိုကြည့်မည် →',
    csv_processing: 'စီမံဆောင်ရွက်နေပါသည်...',
    csv_preview_title: 'ကြိုကြည့်ရှုမှု',
    csv_preview_showing: 'မှတ်တမ်း · ပထမ 5 ခု ပြသနေသည်',
    csv_more_entries: 'မှတ်တမ်း ထပ်ရှိသည်',
    csv_import_btn: 'မှတ်တမ်း {count} ခု Import လုပ်မည်',
    csv_importing: 'Import လုပ်နေပါသည်...',
    csv_cancel: 'မလုပ်တော့ပါ',
    csv_back: '← နောက်သို့',
    csv_done_title: 'Import ပြီးပါပြီ!',
    csv_import_more: 'ထပ်မံ Import လုပ်မည်',
    csv_premium_title: 'Premium အင်္ဂါရပ်',
    csv_premium_desc: 'ဤ အင်္ဂါရပ်သည် Premium အသုံးပြုသူများအတွက်သာ ဖြစ်ပါသည်။',
    csv_select_col: '— ရွေးချယ်ပါ —',

    // PremiumPackage
    premium_pkg_title: '👑 Premium Package',
    premium_pkg_features_header: 'အင်္ဂါရပ်များ',
    premium_pkg_free_col: 'အခမဲ့',
    premium_pkg_pro_col: '👑 Pro',
    premium_pkg_choose_plan: 'အစီအစဥ် ရွေးပါ',
    premium_pkg_payment_method: 'ငွေပေးချေမှု နည်းလမ်း',
    premium_pkg_monthly_label: '၃၀ ရက်',
    premium_pkg_monthly_price: '8,000',
    premium_pkg_monthly_unit: 'ကျပ် / ၃၀ ရက်',
    premium_pkg_yearly_label: '၃၆၅ ရက်',
    premium_pkg_yearly_price: '60,000',
    premium_pkg_yearly_unit: 'ကျပ် / နှစ်',
    premium_pkg_yearly_badge: '39% သက်သာ',
    premium_pkg_copy_btn: 'ကူးမည်',
    premium_pkg_copied: '✓',
    premium_pkg_txn_label: 'ငွေလွှဲ ID',
    premium_pkg_txn_required: '*',
    premium_pkg_txn_placeholder: 'ငွေလွှဲ ID ထည့်ပါ...',
    premium_pkg_screenshot_label: 'ငွေပေးချေမှု Screenshot',
    premium_pkg_screenshot_upload: 'Screenshot တင်ပါ',
    premium_pkg_validation_txn: 'Transaction ID လိုပါသည်',
    premium_pkg_validation_screenshot: 'Screenshot တင်ပါ',
    premium_pkg_submit_btn: '✨ ပေးပို့မည်',
    premium_pkg_submitting: 'ပို့နေပါသည်...',
    premium_pkg_footer: 'Admin မှ စစ်ဆေးပြီး ၂၄ နာရီအတွင်း အတည်ပြုမည်',
    premium_pkg_success_title: 'ငွေပေးချေမှု တင်ပြပြီးပါပြီ!',
    premium_pkg_success_desc: 'အကောင့်ကို စစ်ဆေးနေဆဲဖြစ်ပြီး ၂၄ နာရီအတွင်း အသုံးပြုနိုင်ရန် ဆောင်ရွက်ပေးပါမည်။',
    premium_pkg_back_btn: 'နောက်သို့',
    premium_pkg_feature_receipt: 'ဘောင်ချာ Scan & AI စစ်ဆေးခြင်း',
    premium_pkg_feature_csv: 'CSV ဖိုင် တင်သွင်းခြင်း',
    premium_pkg_feature_autopay: 'အလိုအလျောက် ငွေပေးချေမှု',
    premium_pkg_feature_backup: 'Backup & ပြန်လည်ရယူရန်',
    premium_pkg_feature_notion: 'Notion Sync',
    premium_pkg_feature_support: 'Priority ပံ့ပိုးမှု',
    premium_pkg_feature_manual: 'ကိုယ်တိုင်ထည့်ခြင်း',
    premium_pkg_feature_dashboard: 'Dashboard & Chart များ',
    premium_pkg_feature_export: 'ထုတ်ယူခြင်း (CSV/Excel/PDF)',

    // Admin Panel tabs & buttons
    admin_tab_users: 'အသုံးပြုသူများ',
    admin_tab_payments: 'ငွေပေးချေမှုများ',
    admin_manage_btn: 'စီမံမည်',
    admin_entries_count: 'မှတ်တမ်း',
    admin_user_updated_toast: 'User ပြင်ဆင်ပြီးပါပြီ ✓',
    admin_refresh_btn: 'ပြန်လည်ဆွဲယူမည်',
    admin_loading: 'ခေတ္တစောင့်ပါ...',
    admin_critical_zone: 'အန္တရာယ်ကြီးသောဇုန်',
    admin_session_footer: 'Admin Session တွင် ရှိနေသည်',
    admin_add_days_hint: 'ပေါင်းရန် (+30) · နုတ်ရန် (-3) · မူလ expiry မှ တွက်သည်',

    // Payment statuses & filters
    payment_status_pending: 'စောင့်ဆိုင်းဆဲ',
    payment_status_approved: 'အတည်ပြုပြီး',
    payment_status_rejected: 'ငြင်းပယ်ပြီး',
    payment_filter_all: 'အားလုံး',
    payment_search_placeholder: 'Email သို့မဟုတ် Transaction ID ဖြင့်ရှာပါ...',
    payment_no_results: 'ငွေပေးချေမှု တောင်းဆိုချက် မတွေ့ပါ',
    payment_screenshot_label: 'ငွေပေးချေမှု Screenshot',
    payment_txn_id_label: 'Transaction ID',
    payment_full_details_label: 'အသေးစိတ် အချက်အလက်',
    payment_approve_btn: 'အတည်ပြုမည်',
    payment_undo_warning: 'ဤလုပ်ဆောင်မှုသည် user ၏ Premium role ကိုပါ ဖြုတ်ချမည်။',
    payment_reject_modal_title: 'ငွေပေးချေမှု ငြင်းပယ်မည်',

    // Premium package new keys
    premium_pkg_days: 'ရက်',
    premium_pkg_currency: 'ကျပ်',
    premium_pkg_per_day: 'ကျပ်/ရက်',
    premium_pkg_badge_popular: '🔥 လူကြိုက်များ',
    premium_pkg_badge_best: '⭐ အကောင်းဆုံး',

    // Notification
    notification_tap_to_read: 'နှိပ်ပြီး အပြည့်ဖတ်ရန်',

    // Premium visibility
    premium_renew_desc: 'Premium သက်တမ်း ထပ်တိုးရန်',
    premium_unlock_desc: 'Premium features အားလုံး ဖွင့်ရန်',

    // Days subtracted toast
    toast_days_subtracted: '{days} ရက် နုတ်ပြီးပါပြီ။',
  },

} as const;

export type StringKey = keyof typeof strings['en'];